# Generated by Django 4.0.4 on 2022-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pswd', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_role', models.CharField(max_length=10)),
                ('recovery_link', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
