# Generated by Django 4.0.4 on 2022-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip_postal', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
