# Generated by Django 4.0.4 on 2022-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0004_alter_projects_project_name_projectlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlog',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
