# Generated by Django 4.0.4 on 2022-04-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0005_projectlog_description_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hrs_per_week',
            field=models.FloatField(default=40),
        ),
    ]
