# Generated by Django 4.0.4 on 2022-04-16 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0006_users_hrs_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_app.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_full_name',
            field=models.CharField(max_length=30),
        ),
    ]
