# Generated by Django 4.0.4 on 2022-04-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0007_alter_projects_project_lead_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_full_name',
            new_name='userFullName',
        ),
    ]
