# Generated by Django 4.0.4 on 2022-04-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0008_rename_user_full_name_users_userfullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='hrs_per_week',
            new_name='hrsPerWeek',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='recovery_link',
            new_name='recoveryLink',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_role',
            new_name='userRole',
        ),
    ]
