# Generated by Django 4.0.4 on 2022-04-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0009_rename_hrs_per_week_users_hrsperweek_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='client_name',
            new_name='clientName',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='zip_postal',
            new_name='zipPostal',
        ),
        migrations.DeleteModel(
            name='ProjectLog',
        ),
    ]
