# Generated by Django 4.0.4 on 2022-04-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0010_rename_client_name_clients_clientname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_lead',
            new_name='projectLead',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_name',
            new_name='projectName',
        ),
    ]
