# Generated by Django 4.0.4 on 2022-04-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0011_rename_project_lead_projects_projectlead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projectLead',
        ),
        migrations.RemoveField(
            model_name='users',
            name='userRole',
        ),
        migrations.AddField(
            model_name='users',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
