# Generated by Django 3.2.9 on 2022-05-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0014_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
