# Generated by Django 3.2.9 on 2022-05-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0015_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_app.country', to_field='country'),
        ),
    ]
