# Generated by Django 3.2.9 on 2022-05-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0017_rename_country_clients_pickedcountry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='pickedCountry',
            new_name='country',
        ),
    ]
