# Generated by Django 3.2.9 on 2022-05-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0018_rename_pickedcountry_clients_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
