# Generated by Django 3.2.9 on 2022-05-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0019_auto_20220503_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='stillActive',
            field=models.BooleanField(default=True),
        ),
    ]
