# Generated by Django 3.2.9 on 2022-05-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_app', '0020_projects_stillactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='stillActive',
            field=models.BooleanField(default=True),
        ),
    ]
